name: labi
description: "Lab-i — Open source image classification tool for researchers"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.7.0
  file_picker: ^8.1.7
  csv: ^6.0.0
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  image_picker: ^1.1.2
  path: ^1.9.1
  image: ^4.8.0
  permission_handler: ^12.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/img/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default:21
  web:
    generate: true
    image_path: "lib/img/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "lib/img/logo.png"
    icon_size: 48 # min:48, max:256, default:48
  macos:
    generate: true
    image_path: "lib/img/logo.png"
  linux:
    generate: true
    image_path: "lib/img/logo.png"

flutter:
  uses-material-design: true
